#define MOTOR_STEERING 25

#define MOTOR_STEPPER_STEP 26
#define MOTOR_STEPPER_DIR 27

#define MOTOR_TURRET_A 19
#define MOTOR_TURRET_B 18

#define MOTOR_BOOM_A 5
#define MOTOR_BOOM_B 17

#define MOTOR_HOOK_A 16
#define MOTOR_HOOK_B 4

#define LEDBLUE 35
#define LEDGREEN 32
#define LEDRED 33

#define BATT_VOLT ADC1_CHANNEL_6 // GPIO 34
